#!/bin/sh
#
# @name M4
#
# @type Quadrotor
#
# Author: Ioannis Mandralis (imandral@caltech.edu)

. ${R}etc/init.d/rc.mc_defaults

# airframe
param set-default CA_AIRFRAME 0

# rotor count
param set-default CA_ROTOR_COUNT 4

# rotor 0
param set-default CA_ROTOR0_PX 0.165
param set-default CA_ROTOR0_PY 0.20473
param set-default CA_ROTOR0_KM 0.09
param set-default CA_ROTOR0_CT 29.0

# rotor 1
param set-default CA_ROTOR1_PX -0.165
param set-default CA_ROTOR1_PY -0.20473
param set-default CA_ROTOR1_KM 0.09
param set-default CA_ROTOR1_CT 29.0

# rotor 2
param set-default CA_ROTOR2_PX 0.165
param set-default CA_ROTOR2_PY -0.20473
param set-default CA_ROTOR2_KM -0.09
param set-default CA_ROTOR2_CT 29.0

# rotor 3
param set-default CA_ROTOR3_PX -0.165
param set-default CA_ROTOR3_PY 0.20473
param set-default CA_ROTOR3_KM -0.09
param set-default CA_ROTOR3_CT 29.0

# set rotor motors
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# set tilt motor
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

# set wheel motors
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108
param set-default PWM_MAIN_FUNC9 109
param set-default PWM_MAIN_FUNC10 110
